### PR TITLE
Feature: add endpoint to get a form file by the filename

### PR DESCRIPTION
**Pull request by wolfderechter**
## ID
DGS-288

## Description

We can’t fetch subsidy forms atm in the subsidy-management app because they aren’t linked to a specific existing subsidy. So we needed to have an endpoint to fetch the subsidy form based by filename.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Related services

- frontend-subsidy-mangement

## How to test

Sending a request like `http://localhost:8888/form-file?filename=%2Fconfig%2Fforms%2Fclimate%2Fstep-submit-pact%2Fversions%2F20210420172044%2Fform.ttl` should return the form.ttl file.

### CODE REVIEW

**Review by aatauil — APPROVED** [review]

**Review by aatauil — APPROVED** [review]

**Comment by cecemel** [comment]
I need more context; how come we end up in this scenario in the first context: fetching data not linked to a subsidy.

**Comment by wolfderechter** [comment]
> I need more context; how come we end up in this scenario in the first context: fetching data not linked to a subsidy.

So we have the subsidy-management frontend that uses subsidiepunt as a backend. We login using the mock-ABB bestuurseenheid and have an overview of all the different subsidies, and their steps/forms. We have access to the form filename, but we can't access an actual existing subsidy-consumption since they might not exist for the mock-ABB bestuurseenheid. So this seemed like the best/easiest approach given we had limited time, otherwise we would have to make sure a subsidy-consumption exists or create it.

**Comment by cecemel** [comment]
Ok that clarifies. Mildly convinced though:
 - this service is really about the management of the applications; not the subsidy or subsidy forms themselves. It seems more appropriate to move this functionality to another simpler service (and re-usable).  Maybe https://github.com/lblod/form-content-service can help? 
   - Subsidy applications management is already a way way too big of a service, adding unrelated features only makes the mudball bigger. 
 - Stepping back; so far I understood the subsidy-management feature would be about managing data of the subsidy; not the form itself?

**Comment by wolfderechter** [comment]
> Stepping back; so far I understood the subsidy-management feature would be about managing data of the subsidy; not the form itself?

Yep the plan was to use it to let business update the dates of subsidies, because it happens a lot and takes some time to manually write the query, peer review, release, deploy etc.

But at the moment it's still a readonly application that shows information on all the subsidies:
- their dates/series
- the criterions aka who can create subsidies
- quick preview of the actual form (what this PR tries to achieve)

**Comment by wolfderechter** [comment]
> this service is really about the management of the applications; not the subsidy or subsidy forms themselves. It seems more appropriate to move this functionality to another simpler service (and re-usable). Maybe https://github.com/lblod/form-content-service can help?

> Subsidy applications management is already a way way too big of a service, adding unrelated features only makes the mudball bigger.

This service is already in our stack and has access to the subsidy files, and it's a specific service for subsidies so it doesn't impact other app's. While the `form-content-service` is used by different applications (mandatenbeheer) it would have to expose subsidy specific files, so doesn't seem like a good fit.

**Pull request closed without merging**
